/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user;

import config.Session;
import config.dbConnector;
import java.awt.Color;
import static java.awt.Color.black;
import static java.awt.Color.red;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import loanhub.loginForm;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author jldak
 */
public class ApplyForm extends javax.swing.JFrame {

    /**
     * Creates new form userDashboard
     */
    public ApplyForm() {
        initComponents();
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("MM-dd-yyyy");
        LocalDate localDate = LocalDate.now();
        adate.setText(""+dtf.format(localDate));
        
        
         displayData();
    }
    
    boolean checkadd = true;
    Color navcolor = new Color(0,51,51);
    Color hovercolor = new Color(255,204,153);

    
    public void displayData(){
        Session sess = Session.getInstance();
    try{
        dbConnector dbc = new dbConnector();
        ResultSet rs = dbc.getData("Select a_id, p_id, a_fname, a_lname, amount, status FROM tbl_apply WHERE a_id != '"+sess.getUid()+"'");
        atable.setModel(DbUtils.resultSetToTableModel(rs));
        rs.close();
    }catch(SQLException ex){
        System.out.println("Error: "+ex.getMessage());
        
    }
}
    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        acc_name = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        acc_lname = new javax.swing.JLabel();
        add = new javax.swing.JPanel();
        addlabel = new javax.swing.JLabel();
        update = new javax.swing.JPanel();
        update1 = new javax.swing.JLabel();
        delete = new javax.swing.JPanel();
        delete1 = new javax.swing.JLabel();
        clear = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        atable = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        pid = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        afname = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        alname = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        acontact = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        astatus = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        aamount = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        aterm = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        aincome = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        pname = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        adate = new javax.swing.JTextField();
        aid = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 51, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jLabel1.setText("Apply Loan Form");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 290, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/dark red (2).jpg"))); // NOI18N
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -90, 800, 150));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 9, -1, 60));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        acc_name.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        acc_name.setForeground(new java.awt.Color(255, 153, 0));
        acc_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acc_name.setText("  Hi User");
        jPanel1.add(acc_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 170, 26));

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user pic (1).png"))); // NOI18N
        jPanel1.add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        acc_lname.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        acc_lname.setForeground(new java.awt.Color(255, 153, 0));
        acc_lname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acc_lname.setText("  Hi User");
        jPanel1.add(acc_lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 170, -1));

        add.setBackground(new java.awt.Color(51, 51, 51));
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addMouseExited(evt);
            }
        });

        addlabel.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        addlabel.setForeground(new java.awt.Color(255, 255, 255));
        addlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addlabel.setText("Add");
        addlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addlabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout addLayout = new javax.swing.GroupLayout(add);
        add.setLayout(addLayout);
        addLayout.setHorizontalGroup(
            addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(addlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        addLayout.setVerticalGroup(
            addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addlabel, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 180, 24));

        update.setBackground(new java.awt.Color(51, 51, 51));
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateMouseExited(evt);
            }
        });
        update.setLayout(null);

        update1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        update1.setForeground(new java.awt.Color(255, 255, 255));
        update1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        update1.setText("Update");
        update1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                update1MouseClicked(evt);
            }
        });
        update.add(update1);
        update1.setBounds(60, 0, 60, 24);

        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 180, 24));

        delete.setBackground(new java.awt.Color(51, 51, 51));
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteMouseExited(evt);
            }
        });
        delete.setLayout(null);

        delete1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        delete1.setForeground(new java.awt.Color(255, 255, 255));
        delete1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        delete1.setText("Delete");
        delete1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delete1MouseClicked(evt);
            }
        });
        delete.add(delete1);
        delete1.setBounds(60, 0, 60, 24);

        jPanel1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 180, 24));

        clear.setBackground(new java.awt.Color(51, 51, 51));
        clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clearMouseExited(evt);
            }
        });
        clear.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Clear");
        clear.add(jLabel7);
        jLabel7.setBounds(60, 0, 60, 24);

        jPanel1.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 180, 24));

        id.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        id.setForeground(new java.awt.Color(255, 255, 255));
        id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        id.setText("User ID:");
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 440, 120, -1));

        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/black backround 700.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 180, 490));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 180, 500));

        jPanel2.setBackground(new java.awt.Color(255, 153, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("Back");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 470, -1, -1));

        atable.setBackground(new java.awt.Color(204, 204, 204));
        atable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(atable);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 580, 150));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-add-new-24.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 30, 30));

        pid.setEnabled(false);
        pid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pidActionPerformed(evt);
            }
        });
        jPanel2.add(pid, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 160, 30));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setText(" First Name");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, 30));
        jPanel2.add(afname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 170, -1));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel15.setText("Last name");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, 30));

        alname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alnameActionPerformed(evt);
            }
        });
        jPanel2.add(alname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 170, -1));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel16.setText("Contact");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));
        jPanel2.add(acontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 170, -1));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel17.setText(" Status");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 440, 60, -1));

        astatus.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        astatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "Approved", "Denied" }));
        astatus.setEnabled(false);
        jPanel2.add(astatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 440, 170, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Date");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, 40, 20));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel18.setText("Amount");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, 20));

        aamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aamountActionPerformed(evt);
            }
        });
        jPanel2.add(aamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, 170, -1));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel19.setText("Term in Months");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 120, -1));
        jPanel2.add(aterm, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 170, -1));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel20.setText("Annual Income");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 120, -1));
        jPanel2.add(aincome, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, 170, -1));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel21.setText(" Type Name");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 202, -1, 40));

        pname.setEnabled(false);
        pname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnameActionPerformed(evt);
            }
        });
        jPanel2.add(pname, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 180, 30));

        jPanel4.setBackground(new java.awt.Color(153, 0, 0));
        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 600, -1));

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        jLabel3.setText("Loan Applications");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, -1));

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 25)); // NOI18N
        jLabel4.setText("Borrowers Information");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 280, -1));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel22.setText("Plan ID");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, 30));

        adate.setEnabled(false);
        jPanel2.add(adate, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 170, -1));

        aid.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        aid.setText("id");
        jPanel2.add(aid, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jLabel6.setText("Application ID:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jLabel8.setText("Search");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, -1, 40));

        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 180, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/red-and-orange-background.jpg"))); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 500));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 600, 500));

        jPanel5.setBackground(new java.awt.Color(102, 0, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 590));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
     
         userDashboard urb = new userDashboard();
        urb.setVisible(true);
        this.dispose();

        
    }//GEN-LAST:event_jLabel5MouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated



  
          
         Session sess = Session.getInstance();  
     id.setText("USER ID: "+sess.getUid());
   
    if(sess.getUid() == 0){
     JOptionPane.showMessageDialog(null, "No account found, Login First");
     loginForm If = new loginForm();
     If.setVisible(true);
     this.dispose();
    }else{
        
    acc_name.setText(""+sess.getFname());
    acc_lname.setText(""+sess.getLname());
    
    }
   acc_name.setText(""+sess.getFname()); 















        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void atableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atableMouseClicked
  

        
         
      int rowIndex = atable.getSelectedRow();
      
      
      if(rowIndex < 0){
          JOptionPane.showMessageDialog(null, "Please select an item!");
      }else{
                  
       try{   
          dbConnector dbc = new dbConnector();
          TableModel tbl = atable.getModel(); 
    ResultSet rs = dbc.getData(
    "SELECT tbl_apply.*, tbl_plan.p_name FROM tbl_apply " + 
    "JOIN tbl_plan ON tbl_apply.p_id = tbl_plan.p_id " + 
    "WHERE tbl_apply.a_id = '" + tbl.getValueAt(rowIndex, 0) + "'"
);

         
          if(rs.next()){  
         
          aid.setText(""+rs.getInt("a_id"));
          pid.setText(""+rs.getInt("p_id"));
          pname.setText(""+rs.getString("p_name"));
          afname.setText(""+rs.getString("a_fname"));
          alname.setText(""+rs.getString("a_lname"));
          acontact.setText(""+rs.getString("a_contact"));
          aamount.setText(""+rs.getString("amount"));
          aterm.setText(""+rs.getString("a_term"));
          aincome.setText(""+rs.getString("a_annual"));
          adate.setText(""+rs.getString("date"));
          astatus.setSelectedItem(""+rs.getString("status"));
          add.setEnabled(false);
          addlabel.setForeground(red);
          checkadd = false;
     
      
         }
      }catch(SQLException ex){
        System.out.println(""+ex);
      }

      }
  
        
        
        
        
        
        
        
        
        
        
        
        
        

    }//GEN-LAST:event_atableMouseClicked

    private void pidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pidActionPerformed

    private void alnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alnameActionPerformed

    private void aamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aamountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aamountActionPerformed

    private void pnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnameActionPerformed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked

this.dispose();
loanTypeTable ltt = new loanTypeTable();
ltt.setVisible(true);




        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseClicked

    private void addlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addlabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_addlabelMouseClicked

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
Session sess = Session.getInstance(); 
if (checkadd) {
    if (pid.getText().isEmpty() || pname.getText().isEmpty() || afname.getText().isEmpty() || alname.getText().isEmpty() || acontact.getText().isEmpty() || aamount.getText().isEmpty()
        || aterm.getText().isEmpty() || aincome.getText().isEmpty() || adate.getText().isEmpty()) {
        
        JOptionPane.showMessageDialog(null, "All fields are required!");
    } else {
        dbConnector dbc = new dbConnector();

        double overallAmount = 0.0;
        double interestAmount = 0.0;
        double monthlyPayment = 0.0;
        double monthlyPrincipal = 0.0;  // <-- added
        double monthlyInterest = 0.0;   // <-- added

        try {
            String planQuery = "SELECT p_interest FROM tbl_plan WHERE p_id = '" + pid.getText() + "'";
            ResultSet rs = dbc.getData(planQuery);
            if (rs.next()) {
                String interestStr = rs.getString("p_interest").replace("%", "").trim(); // ✅ handles "5%" format
                double interest = Double.parseDouble(interestStr);
                double amount = Double.parseDouble(aamount.getText());
                int term = Integer.parseInt(aterm.getText());
                interestAmount = amount * (interest / 100); // ✅ compute only interest
                overallAmount = amount + interestAmount;
                monthlyPayment = overallAmount / term; // ✅ monthly payment = total / term

                monthlyPrincipal = amount / term;     // <-- added calculation
                monthlyInterest = interestAmount / term; // <-- added calculation
            }
        } catch (Exception ex) {
            System.out.println("Interest calculation error: " + ex);
        }

        if (dbc.insertData("INSERT INTO tbl_apply(u_id, p_id, a_fname, a_lname, a_contact, amount, a_term, a_annual, date, status, a_interest, a_overall_amount, a_monthly_payment, a_monthly_principal, a_monthly_interest)"
                + "VALUES('" + sess.getUid() + "','" + pid.getText() + "','" + afname.getText() + "','" + alname.getText() + "','" + acontact.getText()
                + "','" + aamount.getText() + "','" + aterm.getText() + "','" + aincome.getText() + "','" + adate.getText() + "','" + astatus.getSelectedItem()
                + "','" + interestAmount + "','" + overallAmount + "','" + monthlyPayment + "','" + monthlyPrincipal + "','" + monthlyInterest + "')")) {
            
            JOptionPane.showMessageDialog(null, "Application Added");
            displayData();

            checkadd = true;
            addlabel.setForeground(black);

            // ✅ Log the insert action
            try {
                String logQuery = "INSERT INTO tbl_logs (u_id, action, date) VALUES ('"
                        + sess.getUid() + "', 'Added application ID " + pid.getText() + "', NOW())";
                dbc.insertData(logQuery);
            } catch (Exception ex) {
                System.out.println("Log Insert Error: " + ex);
            }

            // Clear fields after successful insert and logging
            pid.setText("");
            pname.setText("");
            afname.setText("");
            alname.setText("");
            acontact.setText("");
            aamount.setText("");
            aterm.setText("");
            aincome.setText("");
            adate.setText("");
            astatus.setSelectedIndex(0);

        } else {
            JOptionPane.showMessageDialog(null, "Error adding data.");
        }
    }
} else {
    JOptionPane.showMessageDialog(null, "Clear the field first");
}

    }//GEN-LAST:event_addMouseClicked

    private void addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseEntered

        add.setBackground(hovercolor);

    }//GEN-LAST:event_addMouseEntered

    private void addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseExited

        add.setBackground(navcolor);

        // TODO add your handling code here:
    }//GEN-LAST:event_addMouseExited

    private void update1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_update1MouseClicked

    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked

  if (aid.getText().isEmpty()) {
    JOptionPane.showMessageDialog(null, "Please select an apply record first");
    return;
}

if (pid.getText().isEmpty() || afname.getText().isEmpty() || 
    alname.getText().isEmpty() || acontact.getText().isEmpty() || 
    aamount.getText().isEmpty() || aterm.getText().isEmpty() || 
    aincome.getText().isEmpty() || adate.getText().isEmpty()) {

    JOptionPane.showMessageDialog(null, "All fields are required!");
    return;
}

dbConnector dbc = new dbConnector();

// 🔢 Get interest percentage from tbl_plan
double interest = 0;
try {
    ResultSet rs = dbc.getData("SELECT p_interest FROM tbl_plan WHERE p_id = '" + pid.getText() + "'");
    if (rs.next()) {
        String interestStr = rs.getString("p_interest").replace("%", "");
        interest = Double.parseDouble(interestStr);
    }
} catch (Exception ex) {
    System.out.println("Interest Fetch Error: " + ex);
}

// 💵 Compute interest amount, overall amount, monthly payment
double amount = Double.parseDouble(aamount.getText());
double interestAmount = amount * (interest / 100);
double overallAmount = amount + interestAmount;

int term = Integer.parseInt(aterm.getText());
double monthlyPayment = overallAmount / term;

// 🔢 Calculate monthly principal and monthly interest (added)
double monthlyPrincipal = amount / term;
double monthlyInterest = interestAmount / term;

String sql = "UPDATE tbl_apply SET p_id = ?, a_fname = ?, a_lname = ?, a_contact = ?, amount = ?, a_term = ?, a_annual = ?, date = ?, a_interest = ?, a_overall_amount = ?, a_monthly_payment = ?, a_monthly_principal = ?, a_monthly_interest = ? WHERE a_id = ?";

boolean updated = dbc.updateDataapply(sql, 
    pid.getText(),
    afname.getText(),
    alname.getText(),
    acontact.getText(),
    aamount.getText(),
    aterm.getText(),
    aincome.getText(),
    adate.getText(),
    String.valueOf(interestAmount),
    String.valueOf(overallAmount),
    String.valueOf(monthlyPayment),
    String.valueOf(monthlyPrincipal),   // added
    String.valueOf(monthlyInterest),    // added
    aid.getText()
);

if (updated) {
    JOptionPane.showMessageDialog(null, "Updated Successfully");
    displayData();
    checkadd = true;
    addlabel.setForeground(Color.BLACK);

    // Log the update action
    try {
        Session sess = Session.getInstance();
        String logQuery = "INSERT INTO tbl_logs (u_id, action, date) VALUES ('" 
                + sess.getUid() + "', 'Updated Application: ID " + aid.getText() + "', NOW())";
        dbc.insertData(logQuery);
    } catch (Exception ex) {
        System.out.println("Log Insert Error: " + ex);
    }

    // Clear fields
    pid.setText("");
    afname.setText("");
    alname.setText("");
    acontact.setText("");
    aamount.setText("");
    aterm.setText("");
    aincome.setText("");
    adate.setText("");
    astatus.setSelectedIndex(0);
} else {
    JOptionPane.showMessageDialog(null, "Update failed. Please check your data.");
}




   // TODO add your handling code here:
    }//GEN-LAST:event_updateMouseClicked

    private void updateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseEntered
        update.setBackground(hovercolor);
        // TODO add your handling code here:
    }//GEN-LAST:event_updateMouseEntered

    private void updateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseExited
        update.setBackground(navcolor);      // TODO add your handling code here:
    }//GEN-LAST:event_updateMouseExited

    private void delete1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_delete1MouseClicked

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked

        
    int confirm = JOptionPane.showConfirmDialog(null, 
    "Are you sure you want to delete Application ID " + aid.getText() + "?", 
    "Confirm Delete", 
    JOptionPane.YES_NO_OPTION);

if (confirm == JOptionPane.YES_OPTION) {
    dbConnector dbc = new dbConnector();

    try {
        // 🗑 Delete application from database
        String deleteQuery = "DELETE FROM tbl_apply WHERE a_id = '" + aid.getText() + "'";
        dbc.updateData(deleteQuery);

        // 📝 Log the delete action
        try {
            Session sess = Session.getInstance();
            String logQuery = "INSERT INTO tbl_logs (u_id, action, date) VALUES ('" +
                              sess.getUid() + "', 'Deleted application: ID " + aid.getText() + "', NOW())";
            dbc.insertData(logQuery);
        } catch (Exception ex) {
            System.out.println("Log Insert Error: " + ex);
        }

        // ✅ Confirmation message
        JOptionPane.showMessageDialog(null, "Application deleted successfully.");

        // 🧹 Clear fields
        aid.setText("");
        pid.setText("");
        pname.setText("");
        afname.setText("");
        alname.setText("");
        acontact.setText("");
        aamount.setText("");
        aterm.setText("");
        aincome.setText("");
        adate.setText("");
        astatus.setSelectedIndex(0);

        // 🔄 Refresh table or data
        displayData();
        checkadd = true;
        addlabel.setForeground(black);

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "Error deleting application: " + ex.getMessage());
    }
}

 
        
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteMouseClicked

    private void deleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseEntered

        delete.setBackground(hovercolor);
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteMouseEntered

    private void deleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseExited

        delete.setBackground(navcolor);
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteMouseExited

    private void clearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseClicked
checkadd = true;
    addlabel.setForeground(black);
           
          pid.setText("");
          pname.setText("");
          afname.setText("");
          alname.setText("");
          acontact.setText("");
          aamount.setText("");
          aterm.setText("");
          aincome.setText("");
          adate.setText("");
          astatus.setSelectedIndex(0);

          
           ApplyForm af = new ApplyForm();
        af.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_clearMouseClicked

    private void clearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseEntered
        clear.setBackground(hovercolor);
    }//GEN-LAST:event_clearMouseEntered

    private void clearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseExited
        clear.setBackground(navcolor);
    }//GEN-LAST:event_clearMouseExited

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased

        DefaultTableModel model = (DefaultTableModel) atable.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        atable.setRowSorter(sorter);

        String searchText = jTextField1.getText();
        sorter.setRowFilter(RowFilter.regexFilter("(?i)" + searchText));

        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApplyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApplyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApplyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApplyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApplyForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField aamount;
    private javax.swing.JLabel acc_lname;
    private javax.swing.JLabel acc_name;
    public javax.swing.JTextField acontact;
    private javax.swing.JTextField adate;
    private javax.swing.JPanel add;
    private javax.swing.JLabel addlabel;
    public javax.swing.JTextField afname;
    private javax.swing.JLabel aid;
    public javax.swing.JTextField aincome;
    public javax.swing.JTextField alname;
    public javax.swing.JComboBox<String> astatus;
    public javax.swing.JTable atable;
    public javax.swing.JTextField aterm;
    private javax.swing.JPanel clear;
    private javax.swing.JPanel delete;
    private javax.swing.JLabel delete1;
    private javax.swing.JLabel id;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    public javax.swing.JTextField pid;
    public javax.swing.JTextField pname;
    private javax.swing.JPanel update;
    private javax.swing.JLabel update1;
    // End of variables declaration//GEN-END:variables
}
