/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user;

import loanhub.*;
import admin.*;
import user.*;
import config.Session;
import config.dbConnector;
import config.passwordHasher;
import java.security.NoSuchAlgorithmException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import loanhub.loginForm;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author jldak
 */
public class loanApplication extends javax.swing.JFrame {

    /**
     * Creates new form userDashboard
     */
    public loanApplication() {
        initComponents();
          displayData();
    }
    
  public void displayData(){
    try {
        dbConnector dbc = new dbConnector();
        ResultSet rs = dbc.getData("SELECT a_id, p_id, a_fname, a_lname, amount, status FROM tbl_apply");
        reportTable.setModel(DbUtils.resultSetToTableModel(rs));
        rs.close();
    } catch(SQLException ex) {
        System.out.println("Error: " + ex.getMessage());
    }
}



    /** 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        reportTable = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 51, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jLabel1.setText("Loan Application");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        id.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        id.setText("Uid");
        jPanel3.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jLabel2.setText("Search");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, -1, 40));

        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, 180, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 9, 760, 80));

        jPanel2.setBackground(new java.awt.Color(255, 153, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("Back");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 100, 40));

        reportTable.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(reportTable);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 6, 620, 300));

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton4.setText("Details");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 100, 40));

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("Print");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 100, 40));

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));
        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 140, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/red-and-orange-background.jpg"))); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 310));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 760, 310));

        jPanel5.setBackground(new java.awt.Color(102, 0, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

        
        
         Session sess = Session.getInstance();  
     id.setText("USER ID: "+sess.getUid());
  
     
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

        
        



   userDashboard urb = new userDashboard();
        urb.setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked

    int rowIndex = reportTable.getSelectedRow();
        

if (rowIndex < 0) {
    JOptionPane.showMessageDialog(null, "Please select an item!");
} else {
    try {
        dbConnector dbc = new dbConnector();
        TableModel tbl = reportTable.getModel();

        ResultSet rs = dbc.getData("SELECT * FROM tbl_apply WHERE a_id = '" + tbl.getValueAt(rowIndex, 0) + "'");

        if (rs.next()) {
            applicationDetails ad = new applicationDetails();
            
            ad.aid.setText("" + rs.getString("a_id"));
            ad.pid.setText("" + rs.getString("p_id"));
            ad.afname.setText("" + rs.getString("a_fname"));
            ad.alname.setText("" + rs.getString("a_lname"));
            ad.acontact.setText("" + rs.getString("a_contact"));
            ad.aamount.setText("" + rs.getString("amount"));
            ad.aterm.setText("" + rs.getString("a_term"));
            ad.aincome.setText("" + rs.getString("a_annual"));
            ad.adate.setText("" + rs.getString("date"));
            ad.astatus.setSelectedItem("" + rs.getString("status"));

        

            ad.setVisible(true);
            this.dispose();
        }
    } catch (SQLException ex) {
        System.out.println("Error: " + ex);
    }
}
    
    
    
    
    
    
    
    
    
    


// TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
int rowIndex = reportTable.getSelectedRow();

if (rowIndex < 0) {
    JOptionPane.showMessageDialog(null, "Please select an item!");
} else {
    try {
        dbConnector dbc = new dbConnector();
        TableModel tbl = reportTable.getModel();

        String query = "SELECT a.*, p.p_interest, u.u_type, u.u_fname, u.u_lname, u.u_id FROM tbl_apply a " +
                       "JOIN tbl_plan p ON a.p_id = p.p_id " +
                       "JOIN tbl_user u ON a.u_id = u.u_id " +
                       "WHERE a.a_id = '" + tbl.getValueAt(rowIndex, 0) + "'";

        ResultSet rs = dbc.getData(query);

        if (rs.next()) {
            reportPrinting ada = new reportPrinting();

            ada.aid.setText("" + rs.getString("a_id"));
            ada.pid.setText("" + rs.getString("p_id"));
            ada.afname.setText("" + rs.getString("a_fname"));
            ada.alname.setText("" + rs.getString("a_lname"));
            ada.acontact.setText("" + rs.getString("a_contact"));
            ada.amount.setText("" + rs.getString("amount"));
            ada.aterm.setText("" + rs.getString("a_term"));
            ada.aincome.setText("" + rs.getString("a_annual"));
            ada.adate.setText("" + rs.getString("date"));
            ada.astatus.setText("" + rs.getString("status"));

            String interestrate = rs.getString("p_interest");
            ada.interestrate.setText(interestrate);

            ada.interest.setText("" + rs.getString("a_interest"));

            ada.overallamount.setText("" + rs.getString("a_overall_amount"));

            try {
                double amount = Double.parseDouble(rs.getString("amount"));
                double total = Double.parseDouble(rs.getString("a_overall_amount"));
                int term = Integer.parseInt(rs.getString("a_term"));
                double interestAmount = total - amount;
                double monthlyPrincipal = amount / term;
                double monthlyInterest = interestAmount / term;
                double monthly = total / term;

                ada.monthlypayment.setText(String.format("%.2f", monthly));
                ada.monthlyprincipal.setText(String.format("%.2f", monthlyPrincipal));
                ada.monthlyinterest.setText(String.format("%.2f", monthlyInterest));
            } catch (Exception e) {
                ada.monthlypayment.setText("Error");
                ada.monthlyprincipal.setText("Error");
                ada.monthlyinterest.setText("Error");
                System.out.println("Monthly payment/principal/interest calc error: " + e);
            }

            try {
                java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("MM-dd-yyyy");
                String today = sdf.format(new java.util.Date());
                ada.dateprint.setText(today);
            } catch (Exception e) {
                ada.dateprint.setText("Error");
                System.out.println("Date print error: " + e);
            }

            ada.afname.setText("" + rs.getString("a_fname"));
            ada.alname.setText("" + rs.getString("a_lname"));

            String applicantFullName = rs.getString("a_fname") + " " + rs.getString("a_lname");
            ada.applicantname.setText(applicantFullName);

            // ✅ Set Transact By using u_id from apply record
            ada.uid.setText("Transact By: " + rs.getString("u_id"));

            // ✅ Use session to get current login user (Prepared By)
            Session sess = Session.getInstance();

            String fullName = sess.getFname() + " " + sess.getLname();
            ada.preparedby.setText(fullName);

            String userType = sess.getType();
            String roleDisplay = "";

            if ("User".equalsIgnoreCase(userType)) {
                roleDisplay = "Loan Officer";
            } else if ("Admin".equalsIgnoreCase(userType)) {
                roleDisplay = "Administrator";
            } else {
                roleDisplay = userType;
            }

            ada.role.setText(roleDisplay);

            ada.setVisible(true);
            this.dispose();
        }
    } catch (SQLException ex) {
        System.out.println("Error: " + ex);
    }
}

    

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased

        DefaultTableModel model = (DefaultTableModel) reportTable.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        reportTable.setRowSorter(sorter);

        String searchText = jTextField1.getText();
        sorter.setRowFilter(RowFilter.regexFilter("(?i)" + searchText));

        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyReleased

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loanApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loanApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loanApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loanApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loanApplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable reportTable;
    // End of variables declaration//GEN-END:variables
}
