/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import user.*;
import admin.*;
import static admin.createuserForm.getHeightFromWidth;
import config.PanelPrinter;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author jldak
 */
public class reportPrintingAdmin extends javax.swing.JFrame {

    /**
     * Creates new form individualPrinting
     */
    public reportPrintingAdmin() {
        initComponents();
    }
    
    
    
    public  ImageIcon ResizeImage(String ImagePath, byte[] pic, JLabel label) {
    ImageIcon MyImage = null;
        if(ImagePath !=null){
            MyImage = new ImageIcon(ImagePath);
        }else{
            MyImage = new ImageIcon(pic);
        }
        
    int newHeight = getHeightFromWidth(ImagePath, label.getWidth());

    Image img = MyImage.getImage();
    Image newImg = img.getScaledInstance(label.getWidth(), newHeight, Image.SCALE_SMOOTH);
    ImageIcon image = new ImageIcon(newImg);
    return image;
}
    
    
    
    
    
    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator6 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        page = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        aid = new javax.swing.JLabel();
        pid = new javax.swing.JLabel();
        afname = new javax.swing.JLabel();
        alname = new javax.swing.JLabel();
        acontact = new javax.swing.JLabel();
        aamount = new javax.swing.JLabel();
        aterm = new javax.swing.JLabel();
        aincome = new javax.swing.JLabel();
        adate = new javax.swing.JLabel();
        astatus = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        preparedby = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        monthlypayment = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        overallamount = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        dateprint = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        interest = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        monthlyinterest = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        monthlyprincipal = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        amount = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        interestrate = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        applicantname = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        role = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel37 = new javax.swing.JLabel();
        uid = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 51, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jLabel1.setText("PRINT PANEL SECTION(ADMIN)");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/dark red (2).jpg"))); // NOI18N
        jLabel14.setText("jLabel10");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -80, 680, 180));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 90));

        page.setBackground(new java.awt.Color(255, 255, 255));
        page.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 51, 0));
        jLabel3.setText("LoanHub");
        page.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 174, 35));

        jSeparator1.setForeground(new java.awt.Color(255, 153, 51));
        page.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 540, 20));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 19)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("A Money Lending Company");
        page.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 230, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("LOAN APPLICANT SUMMARY");
        page.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        jSeparator3.setForeground(new java.awt.Color(255, 153, 51));
        page.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 13, 543, 19));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel23.setText("Application ID");
        jPanel3.add(jLabel23);
        jLabel23.setBounds(50, -20, 97, 19);

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel24.setText("Plan ID");
        jPanel3.add(jLabel24);
        jLabel24.setBounds(90, 10, 70, 30);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel18.setText("First Name");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(70, 50, 75, 19);

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel20.setText("Last Name");
        jPanel3.add(jLabel20);
        jLabel20.setBounds(70, 90, 74, 19);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel19.setText("Contact");
        jPanel3.add(jLabel19);
        jLabel19.setBounds(90, 120, 52, 30);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel11.setText("Amount");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(300, -20, 52, 19);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel12.setText("Term");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(310, 10, 36, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel5.setText("Income");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(300, 50, 49, 19);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel10.setText("Date");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(310, 90, 33, 19);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel6.setText("Status");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(300, 120, 42, 30);

        aid.setText("jLabel2");
        jPanel3.add(aid);
        aid.setBounds(160, -30, 114, 30);

        pid.setText("jLabel2");
        jPanel3.add(pid);
        pid.setBounds(160, 10, 116, 28);

        afname.setText("jLabel2");
        jPanel3.add(afname);
        afname.setBounds(160, 50, 105, 31);

        alname.setText("jLabel2");
        jPanel3.add(alname);
        alname.setBounds(160, 90, 86, 26);

        acontact.setText("jLabel2");
        jPanel3.add(acontact);
        acontact.setBounds(160, 120, 100, 30);

        aamount.setText("jLabel2");
        jPanel3.add(aamount);
        aamount.setBounds(370, -30, 102, 34);

        aterm.setText("jLabel2");
        jPanel3.add(aterm);
        aterm.setBounds(360, 10, 120, 28);

        aincome.setText("jLabel2");
        jPanel3.add(aincome);
        aincome.setBounds(360, 50, 120, 20);

        adate.setText("jLabel2");
        jPanel3.add(adate);
        adate.setBounds(360, 80, 100, 31);

        astatus.setText("jLabel2");
        jPanel3.add(astatus);
        astatus.setBounds(360, 120, 107, 34);

        jSeparator2.setForeground(new java.awt.Color(255, 153, 0));
        jPanel3.add(jSeparator2);
        jSeparator2.setBounds(0, 180, 543, 10);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("LOAN SUMMARY");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(150, 190, 220, 29);

        page.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 540, 220));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        page.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 51, 51));
        jLabel28.setText("      Prepared By:");
        page.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 120, 20));

        preparedby.setForeground(new java.awt.Color(51, 51, 51));
        preparedby.setText("Name");
        page.add(preparedby, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 540, 150, 40));

        jSeparator4.setForeground(new java.awt.Color(255, 153, 0));
        page.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 550, 10));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 51));
        jLabel22.setText("Monthly due");
        page.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 90, 20));

        monthlypayment.setForeground(new java.awt.Color(51, 51, 51));
        monthlypayment.setText("jLabel2");
        page.add(monthlypayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 86, 40));

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 51, 51));
        jLabel26.setText("Amount to pay(total)");
        page.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 140, 20));

        overallamount.setForeground(new java.awt.Color(51, 51, 51));
        overallamount.setText("jLabel2");
        page.add(overallamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 90, 40));

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(51, 51, 51));
        jLabel27.setText("Date Print");
        page.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 480, 70, 30));

        dateprint.setForeground(new java.awt.Color(51, 51, 51));
        dateprint.setText("jLabel2");
        page.add(dateprint, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 480, 90, 30));

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 51, 51));
        jLabel25.setText(" Interest(total)");
        page.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 110, 40));

        interest.setForeground(new java.awt.Color(51, 51, 51));
        interest.setText("jLabel2");
        page.add(interest, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, 107, 40));

        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 51, 51));
        jLabel29.setText(" Interest(monthly)");
        page.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 130, 30));

        monthlyinterest.setForeground(new java.awt.Color(51, 51, 51));
        monthlyinterest.setText("jLabel2");
        page.add(monthlyinterest, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, 107, 30));

        jLabel30.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(51, 51, 51));
        jLabel30.setText("Principal (Monthly)");
        page.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, 130, 30));

        monthlyprincipal.setForeground(new java.awt.Color(51, 51, 51));
        monthlyprincipal.setText("jLabel2");
        page.add(monthlyprincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 450, 90, 30));

        jLabel31.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(51, 51, 51));
        jLabel31.setText("Amount Loan");
        page.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 90, 20));

        amount.setForeground(new java.awt.Color(51, 51, 51));
        amount.setText("jLabel2");
        page.add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 86, 40));

        jLabel32.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(51, 51, 51));
        jLabel32.setText("Interest rate");
        page.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 90, 20));

        interestrate.setForeground(new java.awt.Color(51, 51, 51));
        interestrate.setText("jLabel2");
        page.add(interestrate, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, 86, 40));

        jLabel33.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(51, 51, 51));
        jLabel33.setText("Client's Name:");
        page.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 590, 110, 20));

        applicantname.setForeground(new java.awt.Color(51, 51, 51));
        applicantname.setText("Name");
        page.add(applicantname, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 580, 110, 40));

        jLabel34.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(51, 51, 51));
        jLabel34.setText("Role:");
        page.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 570, 50, 30));

        jLabel35.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(51, 51, 51));
        jLabel35.setText("Signature:");
        page.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 610, 70, 30));

        jLabel36.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(51, 51, 51));
        jLabel36.setText("Signature:");
        page.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 610, 70, 20));

        role.setText("ROLE");
        page.add(role, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 570, -1, 30));
        page.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 630, 110, 10));
        page.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 630, 100, -1));

        jLabel37.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(51, 51, 51));
        jLabel37.setText("Transact by ID:");
        page.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 550, -1, 30));

        uid.setForeground(new java.awt.Color(51, 51, 51));
        uid.setText("Name");
        page.add(uid, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 540, 110, 50));

        jPanel1.add(page, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 540, 660));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 110, 40));

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jButton2.setText("Back");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 110, 40));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/black backround 700.png"))); // NOI18N
        jLabel15.setText("jLabel9");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 110, 280));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 110, 280));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/black backround 700.png"))); // NOI18N
        jLabel16.setText("jLabel9");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 110, 260));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/red-and-orange-background.jpg"))); // NOI18N
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 770));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 770));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed


JPanel myPanel = new JPanel();
PanelPrinter pPrint = new PanelPrinter(page);
pPrint.printPanel();




        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked


 
        






        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    
     loanApplicationAdmin laa = new loanApplicationAdmin ();
            laa.setVisible(true);
            this.dispose();   


// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reportPrintingAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reportPrintingAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reportPrintingAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reportPrintingAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reportPrintingAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel aamount;
    public javax.swing.JLabel acontact;
    public javax.swing.JLabel adate;
    public javax.swing.JLabel afname;
    public javax.swing.JLabel aid;
    public javax.swing.JLabel aincome;
    public javax.swing.JLabel alname;
    public javax.swing.JLabel amount;
    public javax.swing.JLabel applicantname;
    public javax.swing.JLabel astatus;
    public javax.swing.JLabel aterm;
    public javax.swing.JLabel dateprint;
    public javax.swing.JLabel interest;
    public javax.swing.JLabel interestrate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    public javax.swing.JLabel monthlyinterest;
    public javax.swing.JLabel monthlypayment;
    public javax.swing.JLabel monthlyprincipal;
    public javax.swing.JLabel overallamount;
    private javax.swing.JPanel page;
    public javax.swing.JLabel pid;
    public javax.swing.JLabel preparedby;
    public javax.swing.JLabel role;
    public javax.swing.JLabel uid;
    // End of variables declaration//GEN-END:variables
}
